#### READ EVENT

GET {{baseurl}}/v1/events/create
Accept: application/json
Content-Type: application/json

###

POST {{baseurl}}/v1/events
Accept: application/json
Content-Type: application/json

{
  "name": "Event 1",
  "timeZone": "America/New_York",
  "eventDateType": "SPECIFIC_DATES",
  "specificDates": ["2021-12-01", "2021-12-02"],
  "recurringWeekdays": null,
  "startTime": 540,
  "endTime": 1020
}


